### ISSUE TITLE
Fix index page

### ISSUE THREAD

**Issue by davidkane9** [davidkane9/maria#17]

**Comment by s-patkar** [comment]
NOTES:
Change opening sentence
	1) what they argued
	2) resulting controversy
	3) kane argues the data quality means this is garbage
	4) this website provides an overview of this issue
change plot subtitle to "implausibly low" not "lower"

**Comment by s-patkar** [comment]
fixed
refer to (#22)

**Comment by s-patkar** [comment]
Remove "rate" from whole site
remove index title
put graph at top
delete calculation
remove the reference from first page
fix citation and reword
