### ISSUE TITLE
Mortality estimate page

### ISSUE THREAD

**Issue by davidkane9** [davidkane9/maria#18]

**Comment by s-patkar** [comment]
NOTES:
- move authors to homepage (INDEX)
- replace "consequently" in first paragraph
- get better reference for 64 deaths (1st para) (ask reddit, Wikipedia talk page etc.)
- remove "leaves behind a path of destruction", talk abt specific dates and times, it was capitalized
-  October 2017 (Specify direct deaths) 
- July 2018 NEJM is italicized, they ARGUE that the excess mortality was 4625 (add CI)
- Adv. version of Kishore was originally published in May 2018 (final version published in July)
- news articles published in MAY 2018
- link Puerto Rico final study
- August 2018 - cite morgue related study (rafael?, PR Gov?)
        - Essentially conclude with "true" data
        - Do we need to do that study ourselves?

**Comment by s-patkar** [comment]
Fixed 
Refer to #22

**Comment by s-patkar** [comment]
rename title to  "estimating mortality"
"direct" should be in single quotes
rephrase to "rappaport" says that...."
quote all Rappaport sentences QUOTE THEM ALL\
rephrase "the official death toll for maria was 64"
full citation for "64" -> give footnote
remove paragraph titles
footnotes for all timeline objects
remove first 3 timeline sections
remove times
remove all headers, make normal text
add colons

include: sept 20, oct 2017, 
may 2018: split into 2 sentences, give CI

reword may-june 2018 to "kishore et al receives widespread news coverage"
      make all headlines footnotes

reword news article paragraph "all these articles reported 64 and 4xxx without noting that the two numbers are based of different definitions. the official def is based of direct deaths. kishore is based of excess mortality. "

remove official publishing date

rename "George Washington ... reports excess mortality of 2975"

ADD: kane 2018 notes the flawed mortality date underlined in kishore 2018.
