### ISSUE TITLE
Add a page with media coverage

### ISSUE THREAD

**Issue by davidkane9** [davidkane9/maria#8]
And include discussion of how hurricane deaths --- and other deaths from natural disasters --- or normally calculated.

The Government --- i.e., NAOA --- has official documents which describe how it counts deaths from hurricanes. Find those docs, add them to references, quote from them. What is their number for Maria? Why is it so different from Kishore?

**Comment by s-patkar** [comment]
George Washington University quoted (#22)(#14)
